apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: study-api
  template:
    metadata:
      labels:
        app: study-api
    spec:
      containers:
      - name: study-api
        image: study-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
