apiVersion: v1
kind: Service
metadata:
  name: study-api-service
spec:
  type: NodePort
  selector:
    app: study-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
